title: GIUSEPPE SILVI

email: me@giuseppesilvi.com

description: > # Musician

baseurl: "" # the subpath of your site, e.g. /blog

url: "giuseppesilvi.com" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: giuseppesilvi

github_username:  grammaton

google_analytics: UA-59367601-3

disqus_shortname: giuseppesilvi

# Build settings
markdown: kramdown
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

info:
  name: "Giuseppe Silvi"
  country: Rome
  state: IT
