title: GIUSEPPE SILVI

email: grammaton@me.com

description: > #Musician

baseurl: "" # the subpath of your site, e.g. /blog

url: "giuseppesilvi.com" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: giuseppesilvi

github_username:  grammaton

google_analytics: UA-59367601-3

disqus_shortname: giuseppesilvi

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-extlinks

extlinks:
  attributes: {rel: nofollow, target: _blank}
  rel_exclude: ['giuseppesilvi.com']

exclude:
  - Gemfile
  - Gemfile.lock

info:
  name: "Giuseppe Silvi"
  country: Rome
  state: IT

extmaterials: https://raw.githubusercontent.com/grammaton/grammaton-materials/master/
